include_guard(GLOBAL)

set(APPLICATIONS 
    "UART_HAL_ECHO"
    "UART_HAL_TX"
    "UART_LL_ECHO"
    "UART_LL_ECHO_SOS"
    "UART_LL_TX"
    "UART_LL_DMA_ECHO"
    # "UART_LL_DMA_ECHO_SOS"
    "UART_LL_DMA_TX"
)
